name: JRuby Continuous Integration

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  jruby_unit_tests:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - "3306:3306"
    strategy:
      fail-fast: false
    steps:
      - name: Configure git
        run: 'git config --global init.defaultBranch main'
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0

      - name: Install JRuby
        uses: ruby/setup-ruby@036ef458ddccddb148a2b9fb67e95a22fdbf728b # tag v1.160.0
        with:
          ruby-version: jruby-9.4.5.0

      - name: Bundle
        run: bundle install

      - name: Run Unit Tests
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # tag v2.8.3
        with:
          timeout_minutes: 30
          max_attempts: 2
          command:  bundle exec rake test:env[norails,rails61]
        env:
          VERBOSE_TEST_OUTPUT: true
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          JAVA_OPTS: --add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist
          JRUBY_OPTS: --dev


  jruby_multiverse:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        suite: [active_support_broadcast_logger, active_support_logger, activemerchant, agent_only, async_http, bare, deferred_instrumentation, grape, high_security, httpclient, httprb, httpx, json, logger, marshalling, rack, resque, roda, roda_agent_disabled, sequel, sinatra, sinatra_agent_disabled, stripe, thread, tilt, typhoeus]
        # suite: [active_record, active_support_broadcast_logger, active_support_logger, activemerchant, agent_only, async_http, bare, concurrent_ruby, config_file_loading, deferred_instrumentation, elasticsearch, ethon, excon, grape, high_security, httpclient, httprb, httpx, json, logger, marshalling, memcache, mongo, net_http, padrino, rack, rails, rails_prepend, rake, redis, resque, roda, roda_agent_disabled, sequel, sinatra, sinatra_agent_disabled, stripe, thread, tilt, typhoeus]

    steps:
      - name: Configure git
        run: 'git config --global init.defaultBranch main'

      - name: Check out the source code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0

      - name: Install JRuby
        uses: ruby/setup-ruby@036ef458ddccddb148a2b9fb67e95a22fdbf728b # tag v1.160.0
        with:
          ruby-version: jruby-9.4.5.0

      - name: Bundle
        run: bundle install

      - name: Run Multiverse Tests
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # tag v2.8.3
        with:
          timeout_minutes: 45
          max_attempts: 1
          command: "bundle exec rake test:multiverse[${{ matrix.suite }}]"
        env: 
          VERBOSE_TEST_OUTPUT: true
          SERIALIZE: 1
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          JAVA_OPTS: --add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist -Xmx4g -Xms512m
          JRUBY_OPTS: --dev

      - name: Annotate errors
        if: ${{ failure() }}
        uses: ./.github/actions/annotate
