name: Snyk Check

on:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag v4.1.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # tag v1.162.0
        with:
          ruby-version: 3.2
      - name: Bundle
        run: bundle install
      - name: Run Snyk
        uses: snyk/actions/ruby@7fad562681122205233d1242c3bb39598c5393da # tag v.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
